spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  messages:
    basename: message/message
    encoding: UTF-8
  mvc:
    view:
      prefix: /views/
      suffix: .jsp
  servlet:
    multipart:
      file-size-threshold: 1MB
      max-file-size: 100MB
      max-request-size: 100MB

mybatis:
    configuration:
      map-underscore-to-camel-case: true
    type-aliases-package: com.yurim.www.dto
    mapper-locations: mapper/**/*.xml

---
spring:
  profiles:
    active: prod
---
spring:
  profiles:
    active: local