spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://kube.itseasy.site:31039/biblet?&serverTimezone=UTC&autoReconnect=true&allowMultiQueries=true&characterEncoding=UTF-8
    username: miruy
    password: yurim2586
  mvc:
    view:
      prefix: /views/
      suffix: .jsp

mybatis:
    configuration:
      map-underscore-to-camel-case: true
    type-aliases-package: com.yurim.www.dto
    mapper-locations: mapper/**/*.xml